TOP=../..

include $(TOP)/configure/CONFIG

DBD += NDPluginRaw.dbd

INC += NDFileRaw.h

LIBRARY_IOC = NDPluginRAW

NDPluginRAW_SRCS  += NDFileRaw.cpp

include $(ADCORE)/ADApp/commonLibraryMakefile

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE


